[Variables]
Bar_Opacity=ff
Bar_Width =3440
Bar_Height =26
Bar_OffsetX =0
Bar_OffsetY =0

Wallpaper =danis-lou-jfZfdQtcH6k-unsplash.jpg

Color_Scheme1 =292828
Color_Scheme2 =B8A584
Color_Scheme3 =7DAEA3
Color_Scheme4 =FFFFFF
Color_Scheme5 =C2534E

Font_Face=siji
Font_Face2=FontAwesome
Font_Size=10
Font_Size2=9

Shadow=0
Translucent=0

DefaultAddedModules=volume,tray,time,workspacemanager,weather,uptime,allergy,date,stock,netspeed,crypto,awesome

