[Variables]
Bar_Opacity=00
Bar_Width =3440
Bar_Height =40
Bar_OffsetX =0
Bar_OffsetY =12

Section_Height =40
Section_Padding = 12

Color_Scheme1 =114769
Color_Scheme2 =C6C6C6
Color_Scheme3 =1A6F79
Color_Scheme4 =EE6934
Color_Scheme5 =C6C6C6

Font_Face1=PixelMPlus12
Font_Face2=Balthasar Regular NBP
Font_Size=9

Shadow=0
Translucent=0
DefaultAddedModules=startmenu,workspacemanager,tray,music,time,date,volume,weather

